name: Publish EFI archive to jsdelivr CDN
on: 
  push: 
    branches: [ $default_branch ]
  workflow_dispatch: 

jobs:
  publish-efi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Reading config & exporting env
        run: 
          - export VERSION=$(cat Docs/.version)
          - export BUILD_NAME="hasee-tongfang-macos-"$VERSION".js"
      
      - name: Pack EFI files into archive
        run: zip -r $BUILD_NAME . -x '*.git*'

      - name: Release to jsdelivr repo
        env:
          token: ${{ secrets.token }}
        run:
          - git clone https://${token}@github.com/kirainmoe/hasee-tongfang-macos-build build
          - rm -rf build/*.zip build/*.js
          - cp $BUILD_NAME build/$BUILD_NAME
          - cd build
          - git config --global user.name "tongfang-ci-bot"
          - git config --global user.email "tongfang@kirainmoe.com"
          - git add . && git commit -m "Deploy version $BUILD_NAME" && git push --force