name: Publish EFI archive to jsdelivr CDN
on: 
  push: 
    branches: [ $default_branch ]

jobs:
  publish-efi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Reading config & exporting env
        run: export VERSION=$(cat Docs/.version)
        run: export BUILD_NAME="hasee-tongfang-macos-"$VERSION".js"
      
      - name: Pack EFI files into archive
        run: zip -r $BUILD_NAME . -x '*.git*'

      - name: Release to jsdelivr repo
        env:
          token: ${{ secrets.token }}
        run: git clone https://${token}@github.com/kirainmoe/hasee-tongfang-macos-build build
        run: rm -rf build/*.zip build/*.js
        run: cp $BUILD_NAME build/$BUILD_NAME
        run: cd build
        run: git config --global user.name "tongfang-ci-bot"
        run: git config --global user.email "tongfang@kirainmoe.com"
        run: git add . && git commit -m "Deploy version $BUILD_NAME" && git push --force